const tabs = [["favoritter","Favoritter"],["push","Push"],["pull","Pull"],["fullbody","Fullbody"],["crosstrening","Cross"],["core","Core"],["kroppsvekt","Kroppsvekt"],["morgen","Morgen"],["nodokt","Nødøkt"],["plan","Ukeplan"],["bank","Øvelser"],["builder","Bygger"],["history","Historikk"]];
      const favorites = ["Deadlift","Landmine Press","Stangroing","Frontbøy","Floor Press","Inverted Rows","Pushups","Push Press","Shrugs","Bicepscurl","Triceps Extension","Planke/Rollout"];
      const equipment = ["Kroppsvekt","Manualer","Stang","Kabel","Maskin","Kettlebell","Strikk","TRX/slynger","Smith-maskin","Landmine","Medisinball","Annet","Benk","Pullupstang"];
      const groups = {
        push:{Bryst:["Benkpress","Skrå hantelpress","Floor Press","Pushups","Dips","Flyes","Hantelpress","Close Grip Bench Press","Incline Pushups","Ring Pushups","Cable Flyes","Machine Chest Press"],Skuldre:["Landmine Press","Skulderpress","Push Press","Arnold Press","Sidehev","Facepull","Fronthev","Y-Raise","Upright Row","Z-Press","Hantel Skulderpress"],Triceps:["Rope Pushdown","Overhead Triceps Extension","Dips","Triceps Extension","Skull Crushers","Close Grip Pushups","Bench Dips","Triceps Kickback"]},
        pull:{Rygg:["Deadlift","Pullups","Nedtrekk","Stangroing","Seated Row","Enarms Roing","Chest Supported Row","Inverted Rows","T-Bar Row","Meadows Row","Straight Arm Pulldown","Rack Pull","Good Morning"],"Bakside skulder":["Reverse Flyes","Facepull","Band Pull Aparts","Rear Delt Row","Cable Reverse Flyes"],Biceps:["Stangcurl","Hantelcurl","Hammercurl","Bicepscurl","Incline Hantelcurl","Preacher Curl","Cable Curl","Reverse Curl"],Grep:["Farmer's Hold","Dead Hang","Plate Pinch","Suitcase Carry","Wrist Curl"]},
        core:{Mage:["Planke","Hollow Hold","Dead Bug","Situps","Boat Pose","Crunch","Reverse Crunch","Leg Raises","Ab Wheel Rollout"],"Skrå mage":["Sideplanke","Plank Knee To Elbow","Russian Twist","Pallof Press","Wood Chop"],Stabilitet:["Bird Dog","Commandos","Bear Crawl","Shoulder Taps","Stir The Pot"],"Rygg/Core":["Superman","Back Extension","Planke/Rollout","Hip Extension Hold","Copenhagen Plank"]},
        kroppsvekt:{Press:["Pushups","Wall Pushups","Pike Pushups","Dips","Diamond Pushups","Decline Pushups","Hand Release Pushups"],Trekk:["Inverted Rows","Dead Hang","Scapular Pullups","Negative Pullups","Towel Row"],Bein:["Squat","Reverse Lunge","Bulgarian Split Squat","Calf Raises","Step Ups","Cossack Squat","Wall Sit","Single Leg RDL"],Hofte:["Glute Bridge","Hip Thrust","Single Leg Glute Bridge","Frog Pumps"],Rygg:["Superman","Back Extension","Prone Y-T-W","Swimmers"]},
        morgen:{"Morgenrutiner":["Pushups","Alternating Superman","Bird Dog","Glute Bridge","Dead Bug","Standing Hip Hinge Drill","Calf Raises","Tall Posture Hold","Wall Pushups","Arm Circles","Reverse Lunges","Hip Flexor Stretch","Thoracic Rotation","Heel To Toe Balance Walk","Scapular Retractions","Nasal Breathing","Cat Cow","World's Greatest Stretch","Ankle Rocks","Wall Slides"]},
        fullbody:{Favorittbank:favorites,Underkropp:["Goblet Squat","Frontbøy","Romanian Deadlift","Step Ups","Bulgarian Split Squat","Hip Thrust","Calf Raises"],Overkropp:["Hantelpress","Landmine Press","Stangroing","Pullups","Floor Press","Inverted Rows","Facepull"],Kondisjon:["Kettlebell Swing","Sled Push","Battle Ropes","Medicine Ball Slam","Jump Rope"]},
        crosstrening:{Crosstrening:["Pushups","Rows","Air Squats","Burpees","Goblet Hold","Hollow Hold","Plank Walkouts","Dumbbell Deadlift","Mountain Climbers","Push Press","Bent Over Row","Situps","Renegade Rows","Kettlebell Swing","Box Step Overs","Wall Balls","Jump Rope","Walking Lunges","Bear Crawl","Medicine Ball Slam","Devil Press"]}
      };
      const templates = [
        {id:"push-90",cat:"push",name:"Push 90 min",duration:90,desc:"Benkpress: 2 oppvarmingssett, 3 x 6-8",ex:[["Benkpress",3,"6-8"],["Skrå hantelpress",4,"8-12"],["Skulderpress",4,"6-10"],["Sidehev",4,"12-15"],["Facepull",3,"15-20"],["Rope Pushdown",3,"10-12"],["Overhead Triceps Extension",2,"12-15"],["Dips",3,"6-10"]]},
        {id:"push-60",cat:"push",name:"Push 60 min",duration:60,desc:"Rask styrkeøkt med favorittpress.",ex:[["Frontbøy",4,6],["Landmine Press",3,8],["Floor Press",3,"8-10"],["Push Press",3,6],["Pushups",3,"sett"],["Triceps Extension",3,12]]},
        {id:"pull-90",cat:"pull",name:"Pull 90 min",duration:90,desc:"Rygg, bakside skulder, biceps og grep.",ex:[["Pullups/Nedtrekk",3,"6-10"],["Stangroing",4,"6-10"],["Stangcurl",4,"8-12"],["Enarms Hantelroing",3,"8-12"],["Reverse Flyes",3,"12-15"],["Hantelcurl",3,"10-12"],["Hammercurl",2,"12-15"],["Farmer's Hold",2,"sett"]]},
        {id:"pull-60",cat:"pull",name:"Pull 60 min",duration:60,desc:"Kort tung trekkøkt med deadlift.",ex:[["Deadlift",4,5],["Stangroing",3,8],["Seated Row",3,10],["Inverted Rows",3,"10-12"],["Shrugs",3,12],["Bicepscurl",3,"10-12"],["Planke/Rollout",3,"sett"]]},
        {id:"fullbody-styrke",cat:"fullbody",name:"Fullbody Styrke",desc:"Favorittbanken.",ex:favorites.map(n=>[n,3,"8-12"])},
        {id:"fullbody-enkel",cat:"fullbody",name:"Fullbody Enkel",desc:"Velg 6-8 øvelser fra favorittbanken.",ex:favorites.slice(0,8).map(n=>[n,3,"rolig"])},
        {id:"crosstrening-a",cat:"crosstrening",name:"Crosstrening A",duration:30,desc:"10 min AMRAP, 10 min intervall, 10 min styrke.",ex:["Pushups","Rows","Air Squats","Burpees","Goblet Hold","Hollow Hold","Plank Walkouts","Dumbbell Deadlift","Mountain Climbers"].map(n=>[n,1,"AMRAP"])},
        {id:"crosstrening-b",cat:"crosstrening",name:"Crosstrening B",desc:"EMOM, sirkel og finisher.",ex:["Push Press","Bent Over Row","Situps","Pushups","Renegade Rows","Burpees"].map(n=>[n,1,"EMOM"])},
        {id:"morgen-a",cat:"morgen",name:"Morgen A",duration:8,desc:"8 min.",ex:["Pushups","Alternating Superman","Bird Dog","Glute Bridge","Dead Bug","Standing Hip Hinge Drill","Calf Raises","Tall Posture Hold"].map(n=>[n,1,"45 sek"])},
        {id:"morgen-b",cat:"morgen",name:"Morgen B",duration:8,desc:"8 min.",ex:["Wall Pushups","Arm Circles","Reverse Lunges","Hip Flexor Stretch","Thoracic Rotation","Heel To Toe Balance Walk","Scapular Retractions","Nasal Breathing"].map(n=>[n,1,"45 sek"])},
        {id:"nodokt-8",cat:"nodokt",name:"Nødøkt",duration:8,desc:"8 minutter når alt annet ryker.",ex:["Pushups","Inverted Rows","Glute Bridge","Dead Bug","Sideplanke","Dead Hang"].map(n=>[n,1,"AMRAP"])}
      ];
      const allNames = [...new Set([...favorites,...Object.values(groups).flatMap(g=>Object.values(g).flat()),...templates.flatMap(t=>t.ex.map(x=>x[0]))])].sort((a,b)=>a.localeCompare(b,"no"));
      const filterData = {
        muscles:["Bryst","Rygg","Skuldre","Biceps","Triceps","Underarm","Mage","Korsrygg","Sete","Fremside lår","Bakside lår","Legger","Full kropp"],
        movements:["Push (press)","Pull (trekk)","Knebøy","Hoftehengsel","Utfall","Rotasjon","Bæring","Hopp/spenst","Kjerne/stabilitet"],
        levels:["Nybegynner","Middels","Avansert"],
        goals:["Muskelvekst","Styrke","Eksplosivitet","Utholdenhet","Mobilitet","Rehabilitering","Fettforbrenning"],
        bank:["Push","Pull","Bein","Fullkropp","Morgenrutine","Hjemmetrening","Gym","Håndball-spesifikk","Mobilitet","Rehab/skadeforebygging"]
      };
      const contains = (name, words) => words.some(w=>name.toLowerCase().includes(w.toLowerCase()));
      const inGroup = (name, cat, title) => groups[cat] && groups[cat][title] && groups[cat][title].includes(name);
      const metaFor = name => {
        const lower=name.toLowerCase(), push=sameGroup(name,"Pushups")||inGroup(name,"push","Bryst")||inGroup(name,"push","Skuldre")||inGroup(name,"push","Triceps"), pull=sameGroup(name,"Deadlift")||inGroup(name,"pull","Rygg")||inGroup(name,"pull","Bakside skulder")||inGroup(name,"pull","Biceps")||inGroup(name,"pull","Grep"), core=inGroup(name,"core","Mage")||inGroup(name,"core","Skrå mage")||inGroup(name,"core","Stabilitet")||inGroup(name,"core","Rygg/Core");
        let primary = push ? (inGroup(name,"push","Bryst")?"Bryst":inGroup(name,"push","Triceps")?"Triceps":"Skuldre") : pull ? (inGroup(name,"pull","Biceps")?"Biceps":inGroup(name,"pull","Grep")?"Underarm":"Rygg") : core ? (inGroup(name,"core","Rygg/Core")?"Korsrygg":"Mage") : "Full kropp";
        if (contains(name,["Squat","Frontbøy","Lunge","Split Squat","Step Ups","Wall Sit","Air Squats","Cossack"])) primary="Fremside lår";
        if (contains(name,["Deadlift","Hip Thrust","Glute Bridge","Kettlebell Swing","Hip Hinge","Good Morning","RDL","Romanian"])) primary=contains(name,["Hip Thrust","Glute Bridge"])?"Sete":"Bakside lår";
        if (contains(name,["Calf"])) primary="Legger";
        const secondary = [...new Set([push&&"Triceps", push&&"Skuldre", pull&&"Biceps", pull&&"Bakside skulder", core&&"Korsrygg", contains(name,["Squat","Lunge","Step"])&&"Sete", contains(name,["Deadlift","Swing","Good Morning"])&&"Korsrygg"].filter(Boolean).filter(x=>x!==primary))].slice(0,3);
        const equip = [...new Set([contains(name,["Hantel","Dumbbell","Goblet","Renegade","Devil"])&&"Manualer", contains(name,["Stang","Benkpress","Deadlift","Frontbøy","Good Morning","Curl"])&&"Stang", contains(name,["Cable","Kabel","Rope","Pulldown","Nedtrekk","Pushdown"])&&"Kabel", contains(name,["Machine"])&&"Maskin", contains(name,["Kettlebell","Swing"])&&"Kettlebell", contains(name,["Band","Strikk"])&&"Strikk", contains(name,["TRX","Ring"])&&"TRX/slynger", contains(name,["Smith"])&&"Smith-maskin", contains(name,["Landmine"])&&"Landmine", contains(name,["Medicine","Medisinball","Wall Balls","Slam"])&&"Medisinball", contains(name,["Benk","Bench","Floor Press"])&&"Benk", contains(name,["Pullups","Dead Hang","Scapular"])&&"Pullupstang"].filter(Boolean))];
        if (!equip.length) equip.push(contains(name,["Pushups","Planke","Situps","Burpees","Squat","Lunge","Superman","Bird Dog","Hollow","Dead Bug","Bear Crawl","Mountain","Dips"])?"Kroppsvekt":"Annet");
        const movement = contains(name,["Press","Push","Dips","Fly","Extension"])||push?["Push (press)"]:contains(name,["Row","Roing","Pull","Curl","Hang","Shrugs","Nedtrekk"])||pull?["Pull (trekk)"]:contains(name,["Squat","Frontbøy"])?["Knebøy"]:contains(name,["Deadlift","Hinge","Swing","Good Morning","Hip Thrust","Glute Bridge"])?["Hoftehengsel"]:contains(name,["Lunge","Split Squat","Step"])?["Utfall"]:contains(name,["Twist","Rotation","Wood Chop","Pallof"])?["Rotasjon","Kjerne/stabilitet"]:contains(name,["Carry","Farmer","Suitcase","Hold","Pinch"])?["Bæring"]:contains(name,["Jump","Burpees","Wall Balls","Slam"])?["Hopp/spenst"]:["Kjerne/stabilitet"];
        const difficulty = contains(name,["Pullups","Hand","Deficit","Weighted","Ring","Rollout","Copenhagen","Meadows","Devil","Z-Press"])?"Avansert":contains(name,["Wall","Dead Bug","Bird Dog","Glute Bridge","Calf Raises","Nasal","Breathing","Arm Circles"])?"Nybegynner":"Middels";
        const bodyPart = primary==="Full kropp"||contains(name,["Burpees","Devil","Battle","Sled","Jump Rope"])?"Full kropp":["Mage","Korsrygg"].includes(primary)?"Kjerne":["Sete","Fremside lår","Bakside lår","Legger"].includes(primary)?"Underkropp":"Overkropp";
        const load = equip.includes("Kroppsvekt")?"Kroppsvekt":contains(name,["Deadlift","Frontbøy","Benkpress","Rack Pull"])?"Tung":contains(name,["Sidehev","Facepull","Reverse","Curl","Extension","Bird Dog","Dead Bug"])?"Lett":"Moderat";
        const side = contains(name,["Enarms","Single Leg","Suitcase","Bulgarian","Lunge","Step Ups","Sideplanke"])?"Unilateral":"Bilateral";
        const type = contains(name,["Curl","Sidehev","Extension","Fly","Calf","Wrist"])?"Isolasjonsøvelse":contains(name,["Stretch","Rotation","Ankle","Wall Slides","Breathing"])?"Mobilitet":contains(name,["Jump Rope","Battle","Sled","Burpees","Mountain","Wall Balls"])?"Kondisjon":contains(name,["Arm Circles","Scapular","Hinge Drill"])?"Oppvarming":contains(name,["Facepull","Band Pull","Y-Raise","Pallof","Dead Bug","Bird Dog"])?"Assistanseøvelse":"Baseøvelse";
        const goals = [...new Set([["Baseøvelse","Assistanseøvelse"].includes(type)&&"Styrke", ["Baseøvelse","Isolasjonsøvelse","Assistanseøvelse"].includes(type)&&"Muskelvekst", contains(name,["Push Press","Jump","Slam","Swing","Burpees","Sled"])&&"Eksplosivitet", ["Kondisjon"].includes(type)&&"Utholdenhet", ["Mobilitet","Oppvarming"].includes(type)&&"Mobilitet", contains(name,["Facepull","Dead Bug","Bird Dog","Pallof","Band Pull","Scapular","Wall Slides"])&&"Rehabilitering", contains(name,["Burpees","Jump Rope","Mountain","Battle","Sled"])&&"Fettforbrenning"].filter(Boolean))];
        const bankCats = [...new Set([push&&"Push", pull&&"Pull", ["Sete","Fremside lår","Bakside lår","Legger"].includes(primary)&&"Bein", bodyPart==="Full kropp"&&"Fullkropp", groups.morgen.Morgenrutiner.includes(name)&&"Morgenrutine", equip.includes("Kroppsvekt")&&"Hjemmetrening", !equip.includes("Kroppsvekt")&&"Gym", goals.includes("Eksplosivitet")&&"Håndball-spesifikk", type==="Mobilitet"&&"Mobilitet", goals.includes("Rehabilitering")&&"Rehab/skadeforebygging"].filter(Boolean))];
        const tags = [...new Set([primary,...secondary,...equip,...movement,difficulty,...goals,type,bodyPart,load,side,...bankCats,name.toLowerCase()])];
        return {name, aliases: name.includes("Hantel")?[name.replace("Hantel","Dumbbell")]:[], description:`${name} er en ${type.toLowerCase()} for ${primary.toLowerCase()}${secondary.length?` med ${secondary.join(", ").toLowerCase()} som støtte`:""}.`, primary, secondary, equipment:equip, movement, difficulty, goals, type, bodyPart, load, side, ppl:bankCats.find(x=>["Push","Pull","Bein"].includes(x))||"Fullkropp", bankCats, tags};
      };
      const storeKey = "treningsbanken-static-v3";
      let state = JSON.parse(localStorage.getItem(storeKey) || '{"tab":"favoritter","builder":[],"builderName":"Egen økt","builderCat":"favoritter","sessions":[],"notes":{},"plan":{"monday":"push-60","wednesday":"pull-60","friday":"fullbody-styrke"},"energy":3,"sleep":3,"effort":"middels","pain":"","comment":"","rest":{}}');
      const view = document.querySelector("#view");
      const save = () => localStorage.setItem(storeKey, JSON.stringify(state));
      const newSet = (reps="") => ({id:crypto.randomUUID(),weight:"",reps,done:false});
      const entry = (name, sets=3, reps="") => ({name, sets:Array.from({length:Math.max(1,Number(sets)||1)},()=>newSet(typeof reps==="number"?reps:"")), targetReps:reps, rest:90, note:""});
      const setsOf = e => Array.isArray(e.sets) ? e.sets : Array.from({length:Number(e.sets)||1},()=>newSet(e.reps||""));
      const volumeEntry = e => setsOf(e).reduce((s,x)=>s+(Number(x.weight)||0)*(Number(x.reps)||0),0);
      const format = e => setsOf(e).filter(x=>x.weight||x.reps).map(x=>`${x.weight?`${x.weight} kg x `:""}${x.reps||"?"}`).join(", ") || `${e.targetReps||"registrer"}`;
      const records = name => state.sessions.flatMap(s=>s.ex).filter(e=>e.name===name).flatMap(setsOf).reduce((r,s)=>{const w=Number(s.weight)||0, reps=Number(s.reps)||0, vol=w*reps, orm=w*(1+reps/30); return {w:Math.max(r.w,w), reps:Math.max(r.reps,reps), vol:Math.max(r.vol,vol), orm:Math.max(r.orm,orm)};},{w:0,reps:0,vol:0,orm:0});
      const lastEntries = name => state.sessions.flatMap(s=>s.ex.filter(e=>e.name===name).map(e=>({...e,date:s.date}))).slice(0,5);
      const alternatives = name => allNames.filter(n=>n!==name && (sameGroup(name,n)||favorites.includes(n))).slice(0,4);
      const sameGroup = (a,b) => Object.values(groups).some(g=>Object.values(g).some(list=>list.includes(a)&&list.includes(b)));
      const imageFor = name => name.includes("Deadlift")||name.includes("Hinge")?"hinge":name.includes("Frontbøy")||name==="Squat"||name.includes("Lunge")||name.includes("Split Squat")?"squat":sameGroup(name,"Pushups")?"push":sameGroup(name,"Deadlift")||sameGroup(name,"Stangroing")?"pull":sameGroup(name,"Planke")||sameGroup(name,"Dead Bug")?"core":"general";
      const stepsFor = name => imageFor(name)==="hinge"?["Stå med vekten over midtfoten.","Trekk brystet opp og hold ryggen lang.","Press gulvet bort med stangen tett på kroppen.","Lås ut kontrollert og senk samme vei."]:imageFor(name)==="squat"?["Sett føttene stabilt og finn buktrykket.","Senk deg kontrollert med knær over tær.","Hold full fot i gulvet og brystet høyt.","Press opp uten å miste posisjon."]:imageFor(name)==="push"?["Sett skuldrene og stram kroppen.","Senk kontrollert til bunnposisjon.","Hold kort kontroll i bunn.","Press opp med jevn kraft."]:imageFor(name)==="pull"?["Start med lang rygg og aktive skulderblad.","Trekk albuen i riktig bane.","Hold kort kontroll i topposisjon.","Senk rolig tilbake."]:["Finn nøytral rygg og rolig pust.","Stram mage og sete.","Hold posisjonen uten kompensasjon.","Stopp når teknikken glipper."];
      const regressionsFor = name => name==="Pushups"?["Wall Pushups","Incline Pushups","Knee Pushups"]:name==="Deadlift"?["Standing Hip Hinge Drill","Dumbbell Deadlift","Block Pull"]:name.includes("Pullups")?["Dead Hang","Scapular Pullups","Nedtrekk"]:imageFor(name)==="core"?["Dead Bug","Planke","Bird Dog"]:["Lavere belastning","Kortere bevegelse","Roligere tempo"];
      const progressionsFor = name => name==="Pushups"?["Tempo Pushups","Feet Elevated Pushups","Weighted Pushups"]:name==="Deadlift"?["Paused Deadlift","Deficit Deadlift","Tyngre toppsett"]:name.includes("Pullups")?["Pullups","Weighted Pullups","Chest-to-bar Pullups"]:imageFor(name)==="core"?["Lengre hold","Rollout","Loaded Carry"]:["Mer belastning","Flere reps","Lengre tid under spenning"];
      const list = items => `<ul class="compactList">${items.map(x=>`<li>${x}</li>`).join("")}</ul>`;
      const startFor = name => imageFor(name)==="hinge"?"Stå med vekten over midtfoten, hofter bak, lang rygg og aktivt buktrykk. Hold belastningen tett på kroppen.":imageFor(name)==="squat"?"Stå stabilt med hele foten i gulvet. Spenn mage og øvre rygg før du starter senkefasen.":imageFor(name)==="push"?"Sett skulderbladene, finn stabil fot- eller håndplassering og hold kroppen stram før første repetisjon.":imageFor(name)==="pull"?"Start med lang rygg, nøytral nakke og aktive skulderblad. La armene være lange før trekket.":"Finn nøytral rygg, rolig pust og en posisjon du kan kontrollere uten kompensasjon.";
      const breathingFor = name => imageFor(name)==="core"?"Pust rolig bak buktrykket. Hold spenningen uten å holde pusten for lenge.":imageFor(name)==="hinge"||imageFor(name)==="squat"?"Pust inn og spenn magen før repetisjonen. Hold trykket gjennom den tyngste delen og pust kontrollert ut på toppen.":"Pust inn før senkefasen. Pust ut når du presser, trekker eller fullfører repetisjonen.";
      const techniqueFor = name => imageFor(name)==="hinge"?["Hold belastningen tett på kroppen.","Bevar lang rygg og aktiv mage.","Start bevegelsen med hoften, ikke korsryggen.","Fullfør med sete og lår, ikke med å lene deg bakover."]:imageFor(name)==="squat"?["Hold hele foten i gulvet.","La knær følge tærne.","Hold brystet høyt og mage spent.","Senk kontrollert før du presser opp."]:imageFor(name)==="push"?["Hold kroppen stram fra start til slutt.","Senk kontrollert før du presser.","Hold håndledd og albuer i en sterk linje.","Press jevnt uten å miste skulderposisjon."]:imageFor(name)==="pull"?["Start trekket med skulderbladene.","Hold ryggen stabil gjennom hele settet.","Trekk albuen i en naturlig bane.","Senk kontrollert og unngå rykk."]:["Hold nøytral rygg.","Stram mage og sete lett.","Beveg deg rolig og kontrollert.","Avslutt settet når teknikken glipper."];
      const mistakesFor = name => imageFor(name)==="hinge"?["Runder korsryggen: reduser vekt og tren hoftehengsel.","Belastningen driver bort fra kroppen: trekk den tettere inn.","Rykker fra gulvet: bygg trykk før du løfter.","Overstrekker på toppen: stopp i strak, stabil posisjon."]:imageFor(name)==="squat"?["Hælene løfter seg: kort ned dybden og jobb med ankelkontroll.","Knær faller inn: press knærne lett ut over tærne.","Mister buktrykk: pust inn og spenn før hver repetisjon.","Faller fremover: senk vekt og hold brystet høyere."]:imageFor(name)==="push"?["Skuldre sklir frem: sett skulderbladene før start.","Korsryggen svaier: stram mage og sete.","For kort bevegelse: bruk lettere variant og full kontroll.","Albuer flarer ukontrollert: finn en sterkere albuebane."]:imageFor(name)==="pull"?["Drar med fart: senk belastningen og stopp i topposisjon.","Skuldre trekkes opp: hold nakken lang og skuldre ned.","Mister ryggposisjon: støtt kroppen bedre eller bruk lavere vekt.","Halve repetisjoner: bruk kontrollert full bevegelse."]:["Holder pusten for lenge: pust rolig og jevnt.","Mister nøytral rygg: kort ned settet.","Jager tempo: senk farten og prioriter kontroll.","Fortsetter etter teknikkfall: stopp settet tidligere."];
      const cuesFor = name => imageFor(name)==="hinge"?["Lang rygg","Stang tett","Press gulvet","Hofter gjennom"]:imageFor(name)==="squat"?["Full fot","Knær over tær","Bryst opp","Press opp"]:imageFor(name)==="push"?["Stram kropp","Kontroll ned","Press jevnt","Lås sterkt"]:imageFor(name)==="pull"?["Skuldre ned","Albue bak","Rolig ned","Lang nakke"]:["Ribbein ned","Rolig pust","Hold linjen","Stopp rent"];
      const repsFor = m => m.type==="Kondisjon"?{strength:"4-8 kraftfulle drag/intervaller",hypertrophy:"8-15 reps",endurance:"30-60 sek eller 15-30 reps"}:m.type==="Mobilitet"||m.type==="Oppvarming"?{strength:"Ikke hovedvalg",hypertrophy:"Ikke hovedvalg",endurance:"30-60 sek rolig kontroll"}:m.type==="Isolasjonsøvelse"?{strength:"6-10 reps",hypertrophy:"10-20 reps",endurance:"15-30 reps"}:{strength:"3-6 reps",hypertrophy:"6-12 reps",endurance:"12-20 reps"};
      const safetyFor = name => imageFor(name)==="hinge"?["Start lett til ryggen holder posisjon.","Avbryt ved skarp smerte i rygg eller hofte.","Ikke maks tungt når du er sliten i korsrygg."]:imageFor(name)==="squat"?["Bruk belastning du kan kontrollere i full fot.","Stopp hvis knær, hofte eller rygg gir skarp smerte.","Øk dybde og vekt gradvis."]:imageFor(name)==="push"?["Hold skulderen smertefri gjennom hele bevegelsen.","Velg lettere variant ved tap av kroppslinje.","Unngå å låse deg fast i smertefull albuebane."]:imageFor(name)==="pull"?["Unngå rykk hvis albue eller skulder er irritert.","Hold nakken avslappet og ryggen stabil.","Reduser vekt hvis grepet bestemmer teknikken."]:["Hold kontrollert tempo.","Stopp før teknikken bryter sammen.","Velg smertefri bevegelsesbane."];
      const progression = name => lastEntries(name).reverse().map(e=>Math.max(...setsOf(e).map(s=>Number(s.weight)||Number(s.reps)||0),0)).filter(Boolean).slice(-8);
      const spark = points => `<div class="spark">${points.length?points.map(p=>`<span style="height:${Math.max(18,p/Math.max(...points)*100)}%"></span>`).join(""):""}</div>`;
      const suggestion = e => { const done=setsOf(e).filter(s=>s.weight||s.reps); const last=lastEntries(e.name)[0]; if(!done.length) return last?`Sist: ${format(last)}`:"Logg første økt for forslag."; const target=Number(String(e.targetReps||"").match(/\d+$/)?.[0]||0); const hit=target&&done.every(s=>Number(s.reps)>=target); const maxW=Math.max(...done.map(s=>Number(s.weight)||0)); return hit&&maxW?`Neste gang: prøv ${maxW+2.5} kg hvis teknikken var god.`:last?`Hold samme vekt til alle sett treffer målet. Sist: ${format(last)}`:"Bygg rolig med god teknikk."; };
      function renderShell() {
        document.querySelector("#tabs").innerHTML = tabs.map(([id,label])=>`<button class="tab ${state.tab===id?"active":""}" data-tab="${id}">${label}</button>`).join("");
        document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab; save(); render();});
        const recent=state.sessions[0], monthAgo=Date.now()-30*24*60*60*1000;
        document.querySelector("#lastSession").textContent = recent?`Sist: ${recent.name}`:"Klar for første logg";
        document.querySelector("#monthCount").textContent = `${state.sessions.filter(s=>new Date(s.date).getTime()>=monthAgo).length} økter / 30d`;
        document.querySelector("#volumeCount").textContent = `${Math.round(state.sessions.reduce((sum,s)=>sum+s.ex.reduce((x,e)=>x+volumeEntry(e),0),0)).toLocaleString("no")} kg volum`;
        document.querySelector("#startFavorites").onclick=()=>start("Favorittøkt","favoritter",favorites.map(n=>entry(n,3,"registrer")));
        document.querySelector("#duplicateLast").onclick=()=>{ if(!recent)return; start(`${recent.name} kopi`,recent.cat,recent.ex.map(e=>({...e,sets:setsOf(e).map(s=>({...s,id:crypto.randomUUID(),done:false}))}))); };
      }
      function profile(name) {
        const m=metaFor(name), reps=repsFor(m), alts=alternatives(name), cues=cuesFor(name);
        return `<div class="profileGrid"><section><strong>Startposisjon</strong><p class="muted">${startFor(name)}</p></section><section><strong>Steg-for-steg</strong><ol class="stepList">${stepsFor(name).map(s=>`<li>${s}</li>`).join("")}</ol></section><section><strong>Pusteteknikk</strong><p class="muted">${breathingFor(name)}</p></section><section><strong>God teknikk</strong>${list(techniqueFor(name))}</section><section><strong>Vanlige feil og korrigering</strong>${list(mistakesFor(name))}</section><section><strong>Coaching cues</strong><div class="chipRow">${cues.map(c=>`<span class="tag cue">${c}</span>`).join("")}</div></section><section><strong>Lettere progresjoner</strong>${list(regressionsFor(name))}</section><section><strong>Tyngre progresjoner</strong>${list(progressionsFor(name))}</section><section><strong>Alternative øvelser</strong><div class="chipRow">${alts.map(n=>`<button class="chip" data-add="${n}">${n}</button>`).join("")||'<span class="muted">Ingen nære alternativer funnet.</span>'}</div></section><section><strong>Anbefalte reps</strong><div class="meta"><span><strong>Styrke:</strong> ${reps.strength}</span><span><strong>Muskelvekst:</strong> ${reps.hypertrophy}</span><span><strong>Utholdenhet:</strong> ${reps.endurance}</span></div></section><section><strong>Sikkerhet</strong>${list(safetyFor(name))}</section><section><strong>Tagger for filtrering</strong><p class="muted">${m.tags.slice(0,18).join(", ")}</p></section></div>`;
      }
      function card(name) {
        const r=records(name), recent=lastEntries(name), m=metaFor(name);
        return `<article class="panel grid"><div class="cardTop"><div><h3>${name}</h3><p class="muted">${m.description}</p></div><button class="icon" data-add="${name}">+</button></div><div class="meta summaryMeta"><span><strong>Primær:</strong> ${m.primary}</span><span><strong>Utstyr:</strong> ${m.equipment.join(", ")}</span><span><strong>Nivå:</strong> ${m.difficulty}</span><span><strong>Mål:</strong> ${m.goals.slice(0,2).join(", ")}</span></div><div class="tags">${favorites.includes(name)?'<span class="tag">Favoritt</span>':""}${m.bankCats.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join("")}${m.tags.slice(0,4).map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="records"><span>Sist: ${recent[0]?format(recent[0]):"ikke logget"}</span><span>Vekt PR: ${r.w?r.w+" kg":"ingen"}</span><span>Reps PR: ${r.reps||"ingen"}</span><span>1RM est.: ${r.orm?Math.round(r.orm)+" kg":"ingen"}</span></div>${spark(progression(name))}<div class="buttons"><button class="secondary" data-detail="${name}">Vis detaljer</button><button class="primary" data-add="${name}">Legg til</button></div></article>`;
      }
      function bindCommon() {
        document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>{state.builder.push(entry(b.dataset.add)); state.tab="builder"; save(); render();});
        document.querySelectorAll("[data-detail]").forEach(b=>b.onclick=()=>{state.detailName=b.dataset.detail; state.detailBack=state.tab; state.tab="detail"; save(); render();});
        document.querySelectorAll("[data-note]").forEach(t=>t.oninput=()=>{state.notes[t.dataset.note]=t.value; save();});
        document.querySelectorAll("[data-start]").forEach(b=>{const t=templates.find(x=>x.id===b.dataset.start); b.onclick=()=>start(t.name,t.cat,t.ex.map(x=>entry(x[0],x[1],x[2])));});
        document.querySelectorAll("[data-copy]").forEach(b=>{const t=templates.find(x=>x.id===b.dataset.copy); b.onclick=()=>start(`${t.name} kopi`,t.cat,t.ex.map(x=>entry(x[0],x[1],x[2])));});
      }
      function renderDetail() {
        const name=state.detailName&&allNames.includes(state.detailName)?state.detailName:allNames[0], m=metaFor(name), r=records(name), recent=lastEntries(name);
        view.innerHTML=`<div class="section"><button class="secondary" id="backDetail">Tilbake</button><button class="primary" data-add="${name}">Legg til i økt</button></div><article class="panel grid detailPanel"><div class="cardTop"><div><h2>${name}</h2><p class="muted">${m.description}</p></div><a class="link" target="_blank" href="https://www.youtube.com/results?search_query=${encodeURIComponent(name+" technique")}">Video</a></div><div class="meta"><span><strong>Primær:</strong> ${m.primary}</span><span><strong>Sekundær:</strong> ${m.secondary.join(", ")||"Ingen"}</span><span><strong>Utstyr:</strong> ${m.equipment.join(", ")}</span><span><strong>Vanskelighet:</strong> ${m.difficulty}</span><span><strong>Bevegelse:</strong> ${m.movement.join(", ")}</span><span><strong>Mål:</strong> ${m.goals.join(", ")}</span><span><strong>Type:</strong> ${m.type}</span><span><strong>Kroppsdel:</strong> ${m.bodyPart}</span><span><strong>Belastning:</strong> ${m.load}</span><span><strong>Side:</strong> ${m.side}</span></div><div class="records"><span>Sist: ${recent[0]?format(recent[0]):"ikke logget"}</span><span>Vekt PR: ${r.w?r.w+" kg":"ingen"}</span><span>Reps PR: ${r.reps||"ingen"}</span><span>1RM est.: ${r.orm?Math.round(r.orm)+" kg":"ingen"}</span><span>Volum PR: ${r.vol?Math.round(r.vol)+" kg":"ingen"}</span></div>${spark(progression(name))}${profile(name)}<textarea data-note="${name}" placeholder="Egne notater">${state.notes[name]||""}</textarea></article>`;
        document.querySelector("#backDetail").onclick=()=>{state.tab=state.detailBack||"bank"; save(); render();};
        bindCommon();
      }
      function templateCard(t) { return `<article class="panel grid"><div class="cardTop"><div><h3>${t.name}</h3><p class="muted">${t.desc||""}</p></div>${t.duration?`<span class="pill">${t.duration} min</span>`:""}</div><div class="list">${t.ex.map(x=>`<div class="historyRow clickableRow"><button class="textButton" data-detail="${x[0]}">${x[0]}</button><span class="muted">${x[1]||""} sett ${x[2]||""}</span></div>`).join("")}</div><div class="buttons"><button class="primary" data-start="${t.id}">Start</button><button class="secondary" data-copy="${t.id}">Dupliser</button></div></article>`; }
      function start(name,cat,ex) { state.builderName=name; state.builder=ex; state.builderCat=cat; state.startedAt=Date.now(); state.energy=3; state.sleep=3; state.effort="middels"; state.pain=""; state.comment=""; state.tab="builder"; save(); render(); }
      function renderCategory(cat) {
        const tpl=templates.filter(t=>t.cat===cat).map(templateCard).join("");
        const groupHtml=groups[cat]?Object.entries(groups[cat]).map(([title,names])=>`<article class="panel grid"><h3>${title}</h3><div class="list">${names.map(n=>`<div class="bankLine clickableRow"><div><button class="textButton exerciseName" data-detail="${n}">${n}</button><p class="muted">${lastEntries(n)[0]?`Sist: ${format(lastEntries(n)[0])}`:"Øvelse"}</p></div><button class="icon small" data-add="${n}">+</button></div>`).join("")}</div></article>`).join(""):"";
        view.innerHTML=`<div class="section"><h2>${tabs.find(t=>t[0]===cat)[1]}</h2></div>${tpl?`<div class="cards">${tpl}</div>`:""}${groupHtml?`<div class="cards">${groupHtml}</div>`:""}`;
        bindCommon();
      }
      function renderBuilder() {
        view.innerHTML=`<div class="section"><h2>Øktbygger</h2></div><article class="panel grid"><input id="builderName" value="${state.builderName||"Egen økt"}"><p class="muted">Logg hvert sett, start hviletimer og lagre økten med kommentar.</p></article><article class="panel grid">${state.builder.length?state.builder.map((e,i)=>builderLine(e,i)).join(""):'<p class="empty">Ingen øvelser i byggeren ennå.</p>'}<div class="sessionMeta"><label>Energi ${state.energy}/5<input type="range" min="1" max="5" value="${state.energy}" id="energy"></label><label>Søvn ${state.sleep}/5<input type="range" min="1" max="5" value="${state.sleep}" id="sleep"></label><label>Følelse<select id="effort"><option ${state.effort==="lett"?"selected":""}>lett</option><option ${state.effort==="middels"?"selected":""}>middels</option><option ${state.effort==="tung"?"selected":""}>tung</option></select></label><label>Vondt<input id="pain" value="${state.pain||""}"></label></div><textarea id="comment" placeholder="Øktkommentar">${state.comment||""}</textarea><div class="buttons"><button class="primary" id="finish">Fullfør og lagre</button><button class="secondary" id="saveProgram">Lagre eget program</button></div></article>`;
        bindBuilder();
      }
      function builderLine(e,i) {
        const restLeft=Math.max(0,Math.ceil(((state.rest||{})[i]||0-Date.now())/1000));
        return `<div class="builderLine"><div class="builderHead"><div><h3>${e.name}</h3><p class="muted">Forrige: ${lastEntries(e.name)[0]?format(lastEntries(e.name)[0]):"ikke logget"}</p></div><div class="buttons"><button class="secondary smallText" data-detail="${e.name}">Detaljer</button><button class="icon small" data-up="${i}">↑</button><button class="icon small" data-down="${i}">↓</button><button class="icon small" data-remove="${i}">×</button></div></div><div class="list">${setsOf(e).map((s,j)=>`<div class="setRow"><span class="setNo">${j+1}</span><label>Kg<input data-i="${i}" data-j="${j}" data-k="weight" value="${s.weight||""}"></label><label>Reps<input data-i="${i}" data-j="${j}" data-k="reps" value="${s.reps||""}"></label><label><input type="checkbox" data-i="${i}" data-j="${j}" data-k="done" ${s.done?"checked":""}> Ferdig</label><button class="icon small" data-rset="${i}:${j}">×</button></div>`).join("")}</div><div class="buttons"><button class="secondary" data-addset="${i}">+ Sett</button>${[60,90,120,180].map(sec=>`<button class="chip ${e.rest===sec?"active":""}" data-rest="${i}:${sec}">${sec}s</button>`).join("")}<button class="primary" data-timer="${i}">${restLeft?restLeft+"s":"Hvile"}</button></div><p class="advice">${suggestion(e)}</p><div class="chipRow">${alternatives(e.name).map(n=>`<button class="chip" data-swap="${i}:${n}">Bytt til ${n}</button>`).join("")}</div><textarea data-enote="${i}" placeholder="Kommentar">${e.note||""}</textarea></div>`;
      }
      function bindBuilder() {
        document.querySelector("#builderName").oninput=e=>{state.builderName=e.target.value; save();};
        ["energy","sleep","effort","pain","comment"].forEach(id=>document.querySelector("#"+id).oninput=e=>{state[id]=e.target.value; save();});
        document.querySelectorAll("[data-k]").forEach(el=>el.oninput=()=>{const e=state.builder[el.dataset.i], sets=setsOf(e); e.sets=sets; sets[el.dataset.j][el.dataset.k]=el.type==="checkbox"?el.checked:el.value; save();});
        document.querySelectorAll("[data-enote]").forEach(el=>el.oninput=()=>{state.builder[el.dataset.enote].note=el.value; save();});
        document.querySelectorAll("[data-addset]").forEach(b=>b.onclick=()=>{const e=state.builder[b.dataset.addset]; e.sets=setsOf(e); e.sets.push(newSet(e.targetReps)); save(); render();});
        document.querySelectorAll("[data-rset]").forEach(b=>b.onclick=()=>{const [i,j]=b.dataset.rset.split(":").map(Number); state.builder[i].sets=setsOf(state.builder[i]).filter((_,x)=>x!==j); if(!state.builder[i].sets.length)state.builder[i].sets=[newSet()]; save(); render();});
        document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.builder.splice(Number(b.dataset.remove),1); save(); render();});
        document.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>move(Number(b.dataset.up),-1));
        document.querySelectorAll("[data-down]").forEach(b=>b.onclick=()=>move(Number(b.dataset.down),1));
        document.querySelectorAll("[data-swap]").forEach(b=>b.onclick=()=>{const [i,n]=b.dataset.swap.split(":"); state.builder[i].name=n; save(); render();});
        document.querySelectorAll("[data-rest]").forEach(b=>b.onclick=()=>{const [i,sec]=b.dataset.rest.split(":"); state.builder[i].rest=Number(sec); save(); render();});
        document.querySelectorAll("[data-timer]").forEach(b=>b.onclick=()=>{state.rest=state.rest||{}; const i=b.dataset.timer; state.rest[i]=Date.now()+(state.builder[i].rest||90)*1000; save(); render();});
        document.querySelector("#finish").onclick=()=>{if(!state.builder.length)return; state.sessions.unshift({date:new Date().toISOString(),name:state.builderName||"Egen økt",cat:state.builderCat||"favoritter",duration:state.startedAt?Math.max(1,Math.round((Date.now()-state.startedAt)/60000)):undefined,ex:state.builder,energy:state.energy,sleep:state.sleep,effort:state.effort,pain:state.pain,comment:state.comment}); state.builder=[]; state.rest={}; state.tab="history"; save(); render();};
        document.querySelector("#saveProgram").onclick=()=>alert("Programmet er lagret i nettleseren som del av øktbyggeren.");
      }
      function move(i,d){const t=i+d;if(t<0||t>=state.builder.length)return;[state.builder[i],state.builder[t]]=[state.builder[t],state.builder[i]];save();render();}
      function renderHistory() {
        const ex=allNames[0], metricPoints=progression(ex);
        view.innerHTML=`<div class="section"><h2>Historikk og progresjon</h2></div><article class="panel grid"><div class="records"><span>Økter totalt: ${state.sessions.length}</span><span>Volum: ${Math.round(state.sessions.reduce((sum,s)=>sum+s.ex.reduce((x,e)=>x+volumeEntry(e),0),0)).toLocaleString("no")} kg</span></div>${spark(metricPoints)}</article>${state.sessions.length?state.sessions.map(s=>`<article class="panel grid"><div class="cardTop"><div><h3>${s.name}</h3><p class="muted">${new Date(s.date).toLocaleDateString("no")} · ${s.cat}${s.duration?` · ${s.duration} min`:""}</p></div><span class="pill">${Math.round(s.ex.reduce((x,e)=>x+volumeEntry(e),0)).toLocaleString("no")} kg</span></div><div class="metaLine"><span>Energi ${s.energy||"-"}/5</span><span>Søvn ${s.sleep||"-"}/5</span><span>${s.effort||"middels"}</span>${s.pain?`<span>${s.pain}</span>`:""}</div><div class="list">${s.ex.map(e=>`<div class="historyRow"><span>${e.name}</span><span class="muted">${format(e)}</span></div>`).join("")}</div>${s.comment?`<p class="muted">${s.comment}</p>`:""}</article>`).join(""):'<p class="empty">Fullfør en økt for å se dato, varighet, øvelser, vekt, reps og kommentarer her.</p>'}`;
      }
      function renderPlan() {
        const days=[["monday","Mandag"],["wednesday","Onsdag"],["friday","Fredag"]];
        view.innerHTML=`<div class="section"><h2>Ukeplan</h2></div><div class="cards three">${days.map(([key,label])=>{const t=templates.find(x=>x.id===state.plan[key])||templates[0];return `<article class="panel grid"><h3>${label}</h3><select data-plan="${key}">${templates.map(x=>`<option value="${x.id}" ${x.id===state.plan[key]?"selected":""}>${x.name}</option>`).join("")}</select><p class="muted">${t.desc||""}</p><button class="primary" data-start="${t.id}">Start</button></article>`}).join("")}</div>`;
        document.querySelectorAll("[data-plan]").forEach(s=>s.onchange=()=>{state.plan[s.dataset.plan]=s.value; save(); render();});
        bindCommon();
      }
      function renderBank() {
        const opts = (label,items) => `<option>${label}</option>${items.map(e=>`<option>${e}</option>`).join("")}`;
        view.innerHTML=`<div class="section"><h2>Øvelsesbank</h2></div><article class="panel grid filterGrid"><input id="search" placeholder="Søk øvelse, tagg eller fritekst"><select id="muscle">${opts("Alle muskler",filterData.muscles)}</select><select id="equip">${opts("Alt utstyr",equipment)}</select><select id="movement">${opts("Alle bevegelser",filterData.movements)}</select><select id="level">${opts("Alle nivå",filterData.levels)}</select><select id="goal">${opts("Alle mål",filterData.goals)}</select><select id="bankCat">${opts("Alle kategorier",filterData.bank)}</select></article><p class="muted" id="resultCount"></p><div class="cards three" id="bankCards"></div>`;
        const apply=()=>{const q=document.querySelector("#search").value.toLowerCase(), muscle=document.querySelector("#muscle").value, eq=document.querySelector("#equip").value, movement=document.querySelector("#movement").value, level=document.querySelector("#level").value, goal=document.querySelector("#goal").value, bankCat=document.querySelector("#bankCat").value; const names=allNames.filter(n=>{const m=metaFor(n), hay=[n,m.description,m.primary,...m.secondary,...m.equipment,...m.movement,m.difficulty,...m.goals,m.type,m.bodyPart,m.load,m.side,m.ppl,...m.bankCats,...m.tags,...m.aliases].join(" ").toLowerCase(); return (!q||hay.includes(q))&&(muscle==="Alle muskler"||m.primary===muscle||m.secondary.includes(muscle))&&(eq==="Alt utstyr"||m.equipment.includes(eq))&&(movement==="Alle bevegelser"||m.movement.includes(movement))&&(level==="Alle nivå"||m.difficulty===level)&&(goal==="Alle mål"||m.goals.includes(goal))&&(bankCat==="Alle kategorier"||m.bankCats.includes(bankCat));}); document.querySelector("#resultCount").textContent=`${names.length} øvelser funnet`; document.querySelector("#bankCards").innerHTML=names.map(card).join("")||'<p class="empty">Ingen treff. Prøv færre filtre.</p>'; bindCommon();};
        ["search","muscle","equip","movement","level","goal","bankCat"].forEach(id=>document.querySelector("#"+id).oninput=apply);
        apply();
      }
      function render() {
        renderShell();
        if(state.tab==="favoritter"){view.innerHTML=`<div class="section"><h2>Favorittøvelser</h2><button class="secondary" id="favBtn">Start økt</button></div><div class="cards three">${favorites.map(card).join("")}</div>`;document.querySelector("#favBtn").onclick=()=>start("Favorittøkt","favoritter",favorites.map(n=>entry(n,3,"registrer")));bindCommon();return;}
        if(state.tab==="builder")return renderBuilder();
        if(state.tab==="detail")return renderDetail();
        if(state.tab==="history")return renderHistory();
        if(state.tab==="bank")return renderBank();
        if(state.tab==="plan")return renderPlan();
        renderCategory(state.tab);
      }
      setInterval(()=>{if(state.tab==="builder"&&Object.values(state.rest||{}).some(t=>t>Date.now()))render();},1000);
      if ("serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{});
      render();




